// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npdfzpaglqgnhfphmpwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZGZ6cGFnbHFnbmhmcGhtcHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTk5ODksImV4cCI6MjA4Nzc5NTk4OX0.A81QZKtTuQE5Pk89ZLsN7iCfFw_rJSttqvakIwvgT2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});